version: "3.3"

services:
  server:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/transforma-minas/
    env_file:
      - .env
    entrypoint: /tmp/run.sh
    #entrypoint: tail -f /dev/null
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  transforma-db:
