version: "3.3"

services:
  server:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/transforma-minas/
    env_file:
      - .env
    entrypoint: /tmp/run.sh
    environment:
      - DB_HOST=transforma_minas_db_1
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  transforma-db:
