version: "3.4"

x-swarm-common: &swarm-common
  networks:
    - public

services:
  server:
    <<: *swarm-common
    image: ${registry}/transforma_server:adicoes-email-prod2
    entrypoint: /tmp/run.sh
    env_file:
      - server-variables.env
    volumes:
      - anexos:/transforma-minas/anexos
  db:
    <<: *swarm-common
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    env_file:
      - db-variables.env
volumes:
  transforma-db:
  anexos:
networks:
  public:
    external:
      name: "nginx_prod_public"
