FROM debian:buster
ARG branch
RUN apt update && apt install php-fpm php-pgsql \
	php-mbstring php-curl php7.3-mysql nginx sendmail git -y
#RUN git clone -b ${branch} repositorio_transforma
ADD transforma/nginx_confs/transforma.conf /etc/nginx/conf.d/
WORKDIR transforma-minas
RUN cp run.sh /tmp

RUN sed -i "s#'hostname' => 'db'#'hostname' => 'transforma_prod2_db'#" application/config/database.php
RUN chmod -R 777 anexos
RUN chmod +x /tmp/run.sh
